output_dir: ../out

dataset: huggan/AFHQv2
img_key: image
img_convert: RGB
img_size: 128

filter: cat

epochs: 300
image_interval: 10
ckpt_interval: 50
batch_size: 16

ema:
  mu: 0.9999

model:
  dim: 32
  dim_mults: [1, 2, 4]
  channels: 3
  s_data: 0.5
  eps: 2e-3

schedule:
  s_1: 150
  s_0: 2
  mu_0: 0.9

  fun:
    rho: 7.0
    eps: ${model.eps}
    T: 80.0
